version: '2'

services:
  dev:
    image: node:6
    network_mode: bridge
    working_dir: /usr/src/app
    ports:
      - "8080"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=silent
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - VIRTUAL_HOST=njordr.app.dnt.privat
      - VIRTUAL_PORT=8080
    command: node ./server.js
