version: '2'

services:
  node:
    image: kkarczmarczyk/node-yarn:latest
    networks:
      - dockerproxy_default
    working_dir: /usr/src/app
    ports:
      - "8080"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=warn
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - VIRTUAL_HOST=njordr.app.dnt.privat
      - VIRTUAL_PORT=8080
    logging:
      options:
        max-size: "500k"
    command: node ./server.js

networks:
  dockerproxy_default:
    external: true
